version: '2'
services:
    aulajdl-app:
        image: aulajdl
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://aulajdl-mysql:3306/aulajdl?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aulajdl-mysql:
        extends:
            file: mysql.yml
            service: aulajdl-mysql
